version: "3.7"
services:
    packet-gateway:
        build: ./packet-gateway
        ports:
            - "3000:3000/udp"
        command: ["dockerize", "-wait", "tcp://rabbitmq:5672", "-timeout", "60s", "go", "run", "main.go"]
    redis:
        image: redis:5.0.3-alpine
    rabbitmq:
        image: rabbitmq:3.7.8-alpine
